#!/usr/bin/env bash


tmux split-window -v -p 30
tmux split-window -h -p 50

tmux send-keys -t -1 "cd angular" Enter
tmux send-keys -t -1 "ng serve" Enter

tmux send-keys "cd go-app" Enter
tmux send-keys "air" Enter


tmux select-pane -t 1
