#!/usr/bin/env bash


tmux split-window -v -l 30%
tmux split-window -h -l 50%

tmux send-keys -t -1 "cd angular" Enter
tmux send-keys -t -1 "nvm use 20" Enter
tmux send-keys -t -1 "ng serve" Enter

tmux send-keys "cd server" Enter
tmux send-keys "air" Enter


tmux select-pane -t 1
